### ISSUE TITLE
needed things / todo

### ISSUE THREAD

**Issue by Desour** [HybridDog/colour_carrier#8]
- [ ] `screenshot.png`
- [x] ~~`description.txt`~~ better mod.conf (with description and dependencies)
~~- [x] `3h-mtg`~~?
~~- [ ] support Wuzzy's doc?~~
- [x] `mod.conf`
- [ ] a nice inventory image
- [ ] ~~use the new names for digilines (`digilines` and not `digiline`, `.` instead of `:` & CO.)~~ ← not needed; add degiline**s** = … in nodedef
- [x] stop z-fighting
- [x] getpos → get_pos
.
.
.

**Comment by Desour** [comment]
Some points were addressed with https://github.com/HybridDog/colour_carrier/commit/f6d1ecd8171393fe146c3e842fd617d5ef01a01e.
